### ISSUE TITLE
Error associating account

### ISSUE THREAD

**Issue by shoff** [shoff/auskf#6]
@tstron Can't associate my Google account even with a brand new database install.
**UserId not found.
**
_Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.InvalidOperationException: UserId not found.
description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.Exception Details: System.InvalidOperationException: UserId not found._

Source Error: 

Line 709:                if (isSuccessful)
Line 710:                {
Line 711:                    result = await this.UserManager.AddLoginAsync(user.Id, info.Login);
Line 712:                    if (result.Succeeded)
Line 713:                    {

Source File: c:\dev\AUSKF\AUSKF\Controllers\AccountController.cs    Line: 711 

Stack Trace: 

[InvalidOperationException: UserId not found.]
   Microsoft.AspNet.Identity.<AddLoginAsync>d__61.MoveNext() +1328
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13855856
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() +31
   AUSKF.Controllers.<ExternalLoginConfirmation>d__56.MoveNext() in c:\dev\AUSKF\AUSKF\Controllers\AccountController.cs:711
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13855856
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult) +93
   System.Web.Mvc.Async.<>c__DisplayClass37.<BeginInvokeAsynchronousActionMethod>b__36(IAsyncResult asyncResult) +22
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +42
   `System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()` +72
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +386
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +42
   System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +38
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +186
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +38
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +29
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +67
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +53
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +36
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +38
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +44
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +67
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +38
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +399
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +157

**Comment by shoff** [comment]
Been working on account creation tonight. I know this worked before. I'll look in to it. Right now trying to finishing up linking when creating a login.

**Comment by shoff** [comment]
@tstron I think you are still logged in as me.

**Comment by tstron** [comment]
You are correct!

**Comment by tstron** [comment]
"Name cannot be null or empty." This is such a shit error message. I have no idea what the cause is and why it was working before but not now.

**Comment by tstron** [comment]
Fixed this. Will be in the next commit.

**Comment by shoff** [comment]
![image](https://cloud.githubusercontent.com/assets/548626/13446162/a60ce86c-dfd6-11e5-8354-1e0bc353dd61.png)


Still get this when I try to register with my google account.

**Comment by tstron** [comment]
![image](https://cloud.githubusercontent.com/assets/14960422/13451151/ee22f882-e001-11e5-866f-78328b5b9f98.png)

**Comment by tstron** [comment]
Fucked up an if statement a little earlier in the code. A lot of that was written quickly in an attempt to get something going and to figure out the other error related to name missing. I cleaned up that controller but it still could use some refactoring.

**Comment by tstron** [comment]
Not sure whats going on with the ClaimsIdentity error I posted a screenshot of. Was working before I synced on Sunday.

**Comment by shoff** [comment]
Still can't associate an account via google or any other provider. I'm really not too keen on the requiring them to search for auskfid before they can register. That's a pretty harsh UX design that will turn off alot of people that would otherwise have registered and then gone on to find their id. I really think that needs to be removed. For instance, I know my Id and I even have access to the code, and I can't figure out what I'm suppose to do to register/link my accounts.

**Comment by tstron** [comment]
I wouldn't be too keen on that either. Thankfully it doesn't require the
user to enter auskf id. Of those four pieces of information none are
required. I'll update the text above to be more clear on that. Try just
putting in your first name. It'll return all "Steve"s in the system. I also
was getting errors last night went testing it but it wasn't any of the
previous errors and I don't think its related to code in that account
controller. The exception, for me anyways, gets thrown on line 150 in
startup.cs (related to SecurityStampValidator ??)

**Comment by tstron** [comment]
I'm around for another half hour if you have a chance to skype before i
leave town.

On Fri, Mar 11, 2016 at 10:22 AM, Travis Stronach <travis.stronach@gmail.com

**Comment by tstron** [comment]
Update the text to the following:

If you are already a registered AUSKF member then please enter any of your
existing information below. No one piece of information is required. If you
find your record you can link it to your new login and your existing
information will be preserved.

Let me know what you think.

On Fri, Mar 11, 2016 at 10:27 AM, Travis Stronach <travis.stronach@gmail.com
> wrote:

> I'm around for another half hour if you have a chance to skype before i
> leave town.
>
> On Fri, Mar 11, 2016 at 10:22 AM, Travis Stronach <

**Comment by tstron** [comment]
Here, I removed the auskf id field since the other three will suffice. Just
comitted it. Also updated the register message again.

On Fri, Mar 11, 2016 at 10:35 AM, Travis Stronach <travis.stronach@gmail.com
> wrote:

> Update the text to the following:
>
> If you are already a registered AUSKF member then please enter any of your
> existing information below. No one piece of information is required. If you
> find your record you can link it to your new login and your existing
> information will be preserved.
>
> Let me know what you think.
>
> On Fri, Mar 11, 2016 at 10:27 AM, Travis Stronach <

**Comment by shoff** [comment]
Awesome, have you noticed that now even if you authenticate correctly the server doesn't think you're logged in? I think I screwed something up with that last week so I'm digging through the providers to figure out WTF I did.
